### ISSUE TITLE
Formatter repeatedly adds new lines to comment blocks

### ISSUE THREAD

**Issue by jsnb-devoted** [mike-lischke/vscode-antlr4#226]
Maybe comments like this aren't supported? I'm a little new to antlr so I don't know what the comment conventions are. My project has a few grammars that I would like to apply a consistent formatter to.

![Screen Recording 2023-10-20 at 10 49 59 AM](https://github.com/mike-lischke/vscode-antlr4/assets/79863718/5044f49a-d424-42b5-987e-3bda92fc5ff6)

**Comment by mike-lischke** [comment]
That's a bug.

**Comment by mike-lischke** [comment]
This is fixed in the now outsourced formatter (see [antlr-format](https://github.com/mike-lischke/antlr-format)).

**Comment by hungtcs** [comment]
I can still reproduce this bug in the latest version. Is this a regression issue?

<img width="779" alt="image" src="https://github.com/user-attachments/assets/98871f0f-2cb3-4297-8a77-9051e7f5ec57">


![2024-11-21 14 31 01](https://github.com/user-attachments/assets/1d31a52d-9617-4269-8253-c7e68ae810c3)
