### ISSUE TITLE
ATN graph cannot be drawn even after code generation.

### ISSUE THREAD

**Issue by smwikipedia** [mike-lischke/vscode-antlr4#28]
After I right click a rule and select "Show ATN graph for rule", I only got this:

![no_atn](https://user-images.githubusercontent.com/999318/37753819-c76b8498-2dd9-11e8-8279-9fa9daf7b091.png)

**Comment by mike-lischke** [comment]
What happens when you change something and save the grammar. Does it show the little busy animation in the status bar? Does the ATN graph show something useful afterwards?

**Comment by smwikipedia** [comment]
Yes, it shows A little busy animation in the status bar after I modify and save the grammar. And I can see new parser files generated. But still cannot see ATN graph.

**Comment by mike-lischke** [comment]
Are there any error messages in the Developer Tools console (see help menu)?

**Comment by smwikipedia** [comment]
I tried below:
Open Help -> Developer Tools -> Console (Choose verbose mode in filter)
Open a .g4 file and modify and save.

What I see:
Busy animation shows.
New parser files generated.
Nothing shows in Developer Tools Console.

**Comment by mike-lischke** [comment]
Does the call graph show up? Does debugging work? The message you see about no ATN data found means the *.interp files couldn't be loaded. The question is: why? Are they generated and reachable?

**Comment by smwikipedia** [comment]
I tried the C# target and Java target. In both scenarios, a `CLexer.interp` file got generated. But I don't know why they cannot be loaded.

**Comment by smwikipedia** [comment]
I just tried the debug. It doesn't work.

My 1st debug settings:

```
{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "antlr4-c",
            "type": "antlr-debug",
            "request": "launch",
            "input": "${workspaceFolder}/${command:AskForTestInput}",
            //"input": "../TestSuite/full.c",
            "grammar": "C.g4",
            "startRule": "compilationUnit",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}
```
I got this error:

![debug1failure](https://user-images.githubusercontent.com/999318/37822668-0c579edc-2ec2-11e8-8387-7d57c7b064a6.png)

My 2nd debug settings:
```

{
    "version": "2.0.0",
    "configurations": [
        {
            "name": "antlr4-c",
            "type": "antlr-debug",
            "request": "launch",
            //"input": "${workspaceFolder}/${command:AskForTestInput}",
            "input": "../TestSuite/full.c",    // <===============HERE changes.
            "grammar": "C.g4",
            "startRule": "compilationUnit",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}

```
![debug2failure](https://user-images.githubusercontent.com/999318/37822719-36626d24-2ec2-11e8-8935-e068f708db34.png)

**Comment by smwikipedia** [comment]
I just tried reinstall Visual Studio Code and the ANTLR extension. Still the same error.

**Comment by mike-lischke** [comment]
That's not a vscode issue. There are several problems at work here.

For debugging:
- The action to ask for that file wasn't recognized, which is totally strange. As a consequence that action was taken as file name.
- In the second case it seems as if the grammar wasn't read from the config, even though it's there. There's a mode where the debugger uses the currently active editor, if that is a grammar, if no grammar is given in the config. If the current editor is not debuggable by the antlr4 extension it shows that other error.

Also for the debugger you need the ATN data. You found the *.interp files in the target folder, right? But for ATN + debugging they must be in the internal `.antlr` folder (which is where your grammar is). Try with internal generation mode. Does this work? Could be something with the interp data move is wrong. These files should be automatically moved from the external output folder to the internal one. You shouldn't even see them.

**Comment by smwikipedia** [comment]
I tried below 2 things:
1. I changed to use `"mode": "internal"`. And I saw below files generated in the `.antlr` folder.
![internal mode](https://user-images.githubusercontent.com/999318/37859211-89bd1e86-2f4b-11e8-990e-809eeb57c533.png)

Then I tried debug by pressing F5. It gave me this:
But the start rule is just there.
![start rule error](https://user-images.githubusercontent.com/999318/37859244-bb2f772a-2f4b-11e8-84ee-69a9fbd3777b.png)

And the ATN graph failed as before.


2. Then I tried `"mode": "external"`. And I manually copy the `*.interp` files to the `.antlr` folder. And then I tried Debug. It gave me the same error as 1. And below are the logs:

```
10:14:03 AM, 3/24/2018
From client: initialize({"clientID":"vscode","adapterID":"antlr-debug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"})
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsStepInTargetsRequest":true}}
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":2,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Interpreter"}]}}
From client: launch({"name":"antlr4-c","type":"antlr-debug","request":"launch","input":"c:\\D\\Sources.2\\tianoad\\Research\\Developer\\mshao\\Research\\CodeCoverage\\TestSuite\\full.c","grammar":"c:\\D\\Sources.2\\tianoad\\Research\\Developer\\mshao\\Research\\CodeCoverage\\grammar\\C.g4","startRule":"compilationUnit","trace":true,"printParseTree":true,"visualParseTree":true,"debugServer":17865,"__sessionId":"42bc26d0-999c-426d-985f-810661544990"})
To client: {"seq":0,"type":"response","request_seq":3,"command":"launch","success":false,"message":"Error while launching debug session: start rule \"compilationUnit\" not found","body":{"error":{"id":1,"format":"Error while launching debug session: start rule \"compilationUnit\" not found"}}}
From client: disconnect({"restart":false})
To client: {"seq":0,"type":"response","request_seq":4,"command":"disconnect","success":true}
```

**Comment by mike-lischke** [comment]
There was an error in the interpreter file name construction, which is fixed now. Until the next release you can split your grammar into individual lexer and parser grammars. This is should work.

**Comment by smwikipedia** [comment]
Thanks for the quick fix. Looking forward to the new release.

**Comment by smwikipedia** [comment]
BTW, I just tried to split my grammar into individual parser and lexer grammars. Unfortunately, still the same error.

[CParser&LexerRules.zip](https://github.com/mike-lischke/vscode-antlr4/files/1844277/CParser.LexerRules.zip)

**Comment by smwikipedia** [comment]
I am not familiar with TS project. Here is what I tried:

1. cloned the repo.
2. run tsc --out SourceContext.js SourceContext.ts

Then I got many errors. Such as:

```
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(13,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(13,8): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(13,13): error TS1005: ';' expected.
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(13,27): error TS1005: ';' expected.
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(13,32): error TS1005: ';' expected.
C:\D\Sources.2\github\vscode-antlr4\src\backend\SourceContext.ts(14,1): error TS1008: Unexpected toke
...

```

**Comment by mike-lischke** [comment]
```bash
Mikes-iMac:vscode-antlr4 mike$ npm update
+ vscode@1.1.14
+ @types/node@8.10.0
updated 11 packages in 7.924s
Mikes-iMac:vscode-antlr4 mike$ npm install

> vscode-antlr4@2.0.0 postinstall /Volumes/Extern/Work/projects/vscode-antlr4
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.17.0
Found minimal version that qualifies engine range: 1.17.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

up to date in 2.685s
Mikes-iMac:vscode-antlr4 mike$ npm run compile

> vscode-antlr4@2.0.0 compile /Volumes/Extern/Work/projects/vscode-antlr4
> tsc --outDir ./out/src

Mikes-iMac:vscode-antlr4 mike$ 
```

Then in out/src/frontend you can find the transpiled SourceContext.js.

**Comment by smwikipedia** [comment]
Below are my try. Bold part is my command input.

**C:\D\Sources.2\github\vscode-antlr4>npm update**
+ fs-extra@5.0.0
+ d3@4.13.0
+ antlr4ts@0.4.1-alpha.0
+ vscode-debugprotocol@1.27.0
+ vscode-debugadapter@1.27.0
+ antlr4-c3@1.1.7
added 394 packages in 22.514s

**C:\D\Sources.2\github\vscode-antlr4>npm install**

> vscode-antlr4@2.0.0 postinstall C:\D\Sources.2\github\vscode-antlr4
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.17.0
Found minimal version that qualifies engine range: 1.17.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/be377c0faf7574a59f84940f593a6849f12e4de7/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

**C:\D\Sources.2\github\vscode-antlr4>npm run compile**

> vscode-antlr4@2.0.0 compile C:\D\Sources.2\github\vscode-antlr4
> tsc --outDir ./out/src

src/backend/ContextSymbolTable.ts(255,38): error TS2554: Expected 0 arguments, but got 1.
src/backend/SourceContext.ts(593,78): error TS2339: Property 'add' does not exist on type 'Symbol[]'.
src/backend/SourceContext.ts(596,9): error TS2322: Type 'Symbol[]' is not assignable to type 'Set<Symbol>'.
  Property 'add' is missing in type 'Symbol[]'.
src/backend/facade.ts(479,38): error TS2554: Expected 0 arguments, but got 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-antlr4@2.0.0 compile: `tsc --outDir ./out/src`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vscode-antlr4@2.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mshao\AppData\Roaming\npm-cache\_logs\2018-03-24T16_02_25_053Z-debug.log

**Comment by mike-lischke** [comment]
Try all that again. I had some changes not yet published in my antlr4-c3 node module.

**Comment by smwikipedia** [comment]
Now the npm commands finished without error. I copied all the js files in output to the extension folder. I can **debug** and see **ATN graphs** now.   Many thanks!


![debug and atn](https://user-images.githubusercontent.com/999318/37866253-3393d64e-2fc3-11e8-9099-73b2475f0ac2.png)

**Comment by mike-lischke** [comment]
If you like rate the extension on the vscode Marketplace.

**Comment by smwikipedia** [comment]
Sure I will rate it 5.😀
