### ISSUE TITLE
Split grammar changes not detected during debug

### ISSUE THREAD

**Issue by obiwanjacobi** [mike-lischke/vscode-antlr4#97]
I have a separate lexer and parser grammar files. When I change the lexer file its changes are not picked up and reflected in the (awesome!) debug view.
I also sometime get an parser error that the TOKEN referenced cannot be found.
`<Error>"<missing TOKEN>"`

I use `options { tokenVocab=<lexer-file>; }` in the parser grammar file to reference the lexer file.
Also use `lexer grammar <lexer-file>` and `parser grammar <parser-file>` in respective files.
The two files live side-by-side in the same directory.

Closing the debug view before debugging again, does not help.
Deleting the temp `.antlr` folder does not help.
When I restart vscode I get one good run.

**Comment by mike-lischke** [comment]
This behavior is by design, because every editor has an own source context (with parser, references etc.). A source context for a parser grammar also knows all dependencies (and will therefore regenerate all target files, including for its dependencies), while one for a lexer grammar only knows it's own rules and those from imported lexer grammars. It does *not* know in which parser grammar it is used (there's no such thing like a back link, it could even be that a lexer grammar is used by multiple parser grammars). Hence, changes in the lexer grammar will not automatically probagate to the parser grammar editor. You will have to trigger parser regeneration in that editor (by doing a dummy change, for example) to pick up changes from dependent lexer grammars.

**Comment by obiwanjacobi** [comment]
So there is no file watcher on parser (root) file dependencies?
I think I've tried touching the parser file as well, but seem to remember that didn't work either. Will give it a try.
Does it matter what (type of) file is the active document? I have found that F5 does not always work when no, or the 'wrong' file (type?) is active - even though the launch definition contains all that should be necessary for running the parser: input, grammar and startRule...?

**Comment by Scratchydisk** [comment]
I have the same issue and can confirm that a dummy change (or real change) in the parser grammar does not resolve the issue.  Additionally, changing just the parser grammar on its own does not trigger parser regeneration either.

The only workaround, as the OP stated, is to close and re-open VisualStudioCode, which then gives you one run before rinsing and repeating.

**Comment by mike-lischke** [comment]
> So there is no file watcher on parser (root) file dependencies?
> I think I've tried touching the parser file as well, but seem to remember that didn't work either. Will give it a try.

If it doesn't work then something else is wrong yet. The workflow is like this:

- On save of a grammar all target files are regenerated (lexer, parser, listeners, visitors and the interpreter data) and the stored interpreter data is refreshed for that file (for code completion, debugging, graphs etc.). Any currently visible graph (e.g. the ATN3PWfVPN#2019
- If the grammar has dependencies (e.g. a split lexer grammar or another parser grammar as import) then the dependencies [are processed as well](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/backend/SourceContext.ts#L723). Their interpreter data is also stored in the source context of the saved grammar tab (because dependencies might not be opened at this moment, so we need that stored separately). This way the source context for a parser grammar gets potential changes from its dependencies.
- If such a dependency is currently opened as well then it will not receive an update (since nothing changed for it). However, if it is saved then the same processing will happen as described in the previous point.
- If a grammar is saved which is a dependency of another grammar then we get in the situation as described in this issue: the current grammar is updated, however not any grammar (and there can be mulitple) that depend on this one.

This problem could be solved if somehow a reference to all dependent grammars could be kept in a referenced grammar. However, I see no clean way to accomplish that. The ANTLR4 syntax does not contain any construct to indicate such references.

> Does it matter what (type of) file is the active document? I have found that F5 does not always work when no, or the 'wrong' file (type?) is active - even though the launch definition contains all that should be necessary for running the parser: input, grammar and startRule...?

Did you get an error message when it failed? There are 2 modes here:

1. If a grammar is specified in the launch options then this grammar is used for debugging, regardless of which editor tab is currently active.
2. If no grammar name is given then the currently active editor is used (if it contains an ANTLR4 parser or combined grammar).

See also the code to [resolve the debug configuration](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/extension.ts#L409).

**Comment by mike-lischke** [comment]
> I have the same issue and can confirm that a dummy change (or real change) in the parser grammar does not resolve the issue. Additionally, changing just the parser grammar on its own does not trigger parser regeneration either.

Please check the `.antlr` sub folder in the grammar folder. Does it contain `.interp` files for all grammars? These files are essential for all graphs and the debugging feature in the extension. Try removing the files if they are there, switch to vscode and save a grammar. Then check if the files are regenerated. I assume here you have either [internal or external code generation enabled](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation).

**Comment by obiwanjacobi** [comment]
I have made a test setup with two g4 files: a lexer and parser file:

testlexer.g4
```
lexer grammar testlexer;
TOKEN: 'token';
```
testparser.g4
```
parser grammar testparser;
options { tokenVocab=testlexer; }
test: TOKEN (TOKEN)*;
```
a test file to be parsed
```
token
```
a vscode launch definition
```
{
            "name": "test antlr",
            "type": "antlr-debug",
            "request": "launch",
            "input": "./grammar/_test/antlr.debug.zs",
            "grammar": "./grammar/_test/testparser.g4",
            "startRule": "test",
            "printParseTree": true,
            "visualParseTree": true
}
```
Hit F5 
```
Parse Tree:
test (
 "token"
)
```
All good. Now edit the lexer file to 'token**s**'
testlexer.g4
```
lexer grammar testlexer;
TOKEN: 'tokens';
```
Hit F5 - nothing changes I still see the old state (I should see an error because the test file still says 'token').

In the `interp` file for the testlexer I see the changes (tokens) 
```
token literal names:
null
'tokens'

token symbolic names:
null
TOKEN

rule names:
TOKEN

channel names:
DEFAULT_TOKEN_CHANNEL
HIDDEN

mode names:
DEFAULT_MODE

atn:
[3, 24715, 42794, 33075, 47597, 16764, 15335, 30598, 22884, 2, 3, 12, 8, 1, 4, 2, 9, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, 3, 3, 3, 3, 2, 2, 2, 11, 2, 3, 3, 2, 2, 2, 3, 5, 3, 2, 2, 2, 5, 6, 7, 118, 2, 2, 6, 7, 7, 113, 2, 2, 7, 8, 7, 109, 2, 2, 8, 9, 7, 103, 2, 2, 9, 10, 7, 112, 2, 2, 10, 11, 7, 117, 2, 2, 11, 4, 3, 2, 2, 2, 3, 2, 2]
```
but the `interp` file for the testparser is unchanged. (Well, there's your problem!)
```
token literal names:
null
'token'

token symbolic names:
null
TOKEN

rule names:
test


atn:
[3, 24715, 42794, 33075, 47597, 16764, 15335, 30598, 22884, 3, 3, 12, 4, 2, 9, 2, 3, 2, 3, 2, 7, 2, 7, 10, 2, 12, 2, 14, 2, 10, 11, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 11, 2, 4, 3, 2, 2, 2, 4, 8, 7, 3, 2, 2, 5, 7, 7, 3, 2, 2, 6, 5, 3, 2, 2, 2, 7, 10, 3, 2, 2, 2, 8, 6, 3, 2, 2, 2, 8, 9, 3, 2, 2, 2, 9, 3, 3, 2, 2, 2, 10, 8, 3, 2, 2, 2, 3, 8]
```

Extension version: 2.1.1
System:
```
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by obiwanjacobi** [comment]
After playing with it some more, I see that you can get the parser `.interp` file to update. Even when I delete the entire .antlr (internal) temp directory, it generates again as soon as you touch the lexer or parser files.
So I am beginning to think it is not a dependency/refresh issue - at least not on file level.

It seems that even  with the correct files, the debugger still doesn't show the new results. The would indicate that the state in the extension is not refreshed. Some sort of internal object that is cached and not updated, perhaps?

**Comment by mike-lischke** [comment]
Well, as I wrote, the internal data is refreshed as soon as vscode sends a save message to the extension, for a grammar file.

But you are saying that when you first change the lexer grammar and then do a dumy change in the parser grammar, it will regenerate the target files but not update its internal structures? If that's the case then this is a bug.

**Comment by obiwanjacobi** [comment]
> But you are saying that when you first change the lexer grammar and then do a dumy change in the parser grammar, it will regenerate the target files but not update its internal structures?

Yes that is what I am saying. The result (of these internal structures?) is only changed once after vscode starts. After that it stay the same.

Did you try the test case I described?

**Comment by Scratchydisk** [comment]
> > I have the same issue and can confirm that a dummy change (or real change) in the parser grammar does not resolve the issue. Additionally, changing just the parser grammar on its own does not trigger parser regeneration either.
> 
> Please check the `.antlr` sub folder in the grammar folder. Does it contain `.interp` files for all grammars? These files are essential for all graphs and the debugging feature in the extension. Try removing the files if they are there, switch to vscode and save a grammar. Then check if the files are regenerated. I assume here you have either [internal or external code generation enabled](https://github.com/mike-lischke/vscode-antlr4/blob/master/doc/extension-settings.md#parser-generation).

I've tried as you suggested:

* Confirmed .interm (lexer and grammar) files are in the .antlr folder.
* Saving a grammar results in the lexer and grammar files updating.

However, running the debugger in VS Code shows no difference.  You have to close then re-open VS Code to see the effect of your changes.

It does show how useful your extension is though that I'm doing this many, many times a day!

**Comment by obiwanjacobi** [comment]
Refactoring a single lexer/grammar file, I also see small errors in the graphic (parse tree) debug window. An old rule name I replaced with another is shown (probably same id or something).

So there is another clue that there IS a state problem.

@mike-lischke Any progress on this issue, Mike?

**Comment by obiwanjacobi** [comment]
Okay, it clear to me that you're not going to fix this any time soon.

@mike-lischke
Is there any chance of explaining the code to me a bit so I can have a stab at fixing this myself?
What parts do what and what is the general philosophy of the implementation - that sort of thing.
I know typescript and I know extensions.

**Comment by mike-lischke** [comment]
@obiwanjacobi I played with your test setup from above and what I see is that if you don't save your changed lexer file the next debug session will still use the old lexer grammar. But if you immediately run the debugger again, it works again fine. The problem here is that the debug session starts sooner than the (async) file save action. So, in order to make it work explicitly save your lexer before running the debugger.

**Comment by mike-lischke** [comment]
@Scratchydisk You say, you say the same issue. Is that for a debug session or just simply changes? When I change my lexer without saving the file and go to the parser tab and change something (just a single keypress is enough), it will immediately pick up the changed lexer for me (e.g. show errors for change lexer rule names and provide change code completion items. I cannot see any problem here.

**Comment by mike-lischke** [comment]
@all, I just released a new version of the extension. See if that improves the situation for you.

**Comment by obiwanjacobi** [comment]
I just tried the new version (2.2.3) and for me it does not fix the issue. If saving the lexer file was out of sync with starting the debug session, restarting a new debug session after some time should fix that, right?

**Comment by mike-lischke** [comment]
Yes, exactly. The debugger uses the interpreter data which is currently loaded in the source context or loads it explicitly if not yet done (e.g. for referenced files that have not been loaded into an editor). This happens when the [debug session is launched](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/frontend/AntlrDebugAdapter.ts#L367). This call goes to the [extension facade](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/backend/facade.ts#L631) where the participating source contexts are collected and their interpreter data is checked (and loaded, if necedssary).

**Comment by obiwanjacobi** [comment]
If I put a debug breakpoint on [createDebugger](https://github.com/mike-lischke/vscode-antlr4/blob/6c5a41db9bbc6d368c329da5b78a24fafa718c26/src/backend/facade.ts#L631) I can see that the dependency context (lexer file) is still the old version...

Have no idea where that comes from though....
[2c]

**Comment by mike-lischke** [comment]
The interpreter data is loaded [here](https://github.com/mike-lischke/vscode-antlr4/blob/6c5a41db9bbc6d368c329da5b78a24fafa718c26/src/backend/SourceContext.ts#L1120). That should be called whenever you change the content of the grammar text editor (after a short delay to avoid calling the antlr4 jar too often). Does this happen for you?

**Comment by obiwanjacobi** [comment]
When I save the lexer file I hit `setupInterpreters` twice...?

I was tracing into `SourceContext.parse()`. That seems to be triggered when I change the editor, but not when the file is saved. I think maybe the reparsing is triggered too early and (re)reads the old data?

**Comment by obiwanjacobi** [comment]
When I look at the [`facade.parseGrammar`](https://github.com/mike-lischke/vscode-antlr4/blob/6c5a41db9bbc6d368c329da5b78a24fafa718c26/src/backend/facade.ts#L344) function which calls [`SourceContext.parse`](https://github.com/mike-lischke/vscode-antlr4/blob/6c5a41db9bbc6d368c329da5b78a24fafa718c26/src/backend/SourceContext.ts#L504), it does not re-init the token stream - parse relies on this - just rewinds it and parses. I think somewhere the token stream should be reopened for the new data...

**Comment by Scratchydisk** [comment]
Hi Mike, I've tried the new version, but I'm still getting the same behaviour.

The attached pdf shows screen shots of me adding an error to my test file, debugging it, modifying the lexer to support the change, debugging, modifying the grammar, debugging, restarting VS Code, debugging.

Hope this helps.

[Steps showing VSCode ANTLR Debugging issue.pdf](https://github.com/mike-lischke/vscode-antlr4/files/3858334/Steps.showing.VSCode.ANTLR.Debugging.issue.pdf)

**Comment by obiwanjacobi** [comment]
Ok, I think I have found something.

I was seeing 3 SourceContext objects for my test case with 2 files. The lexer file -that is a dependency to the parser file and the file I was editing - was in there 2 times. Cant be, I hear you say, It's a map that guarantees a unique key. They were unique.

One file path (the key) ended with `path/file.g4` and one ended with `path\file.g4`. This difference exists because when the lexer file is loaded as a dependency (while debugging the parser) its path is built up in code. That code uses a hard coded forward slash. But on Windows, vscode reports the file path with a back-slash. 

This code lives in the backend `facade.ts` in the [`loadDependency`](https://github.com/mike-lischke/vscode-antlr4/blob/6c5a41db9bbc6d368c329da5b78a24fafa718c26/src/backend/facade.ts#L299) method.

The solution is to use a file path separator that is in sync with the operating system its running on. 
When I changed the hard-coded forward slash to a backward one (I am on Windows) it worked like charm.

**Comment by mike-lischke** [comment]
Rats, I didn't expect it to be **that** reason. I wouldn't have found it either on my Mac. Thanks for staying until that was solved! I just wonder why that issue wasn't reported more.

Anyway, I'm glad this is solved now. Many thanks. Will you create a PR (don't forget to sign the contributors.txt file)?

**Comment by obiwanjacobi** [comment]
Nah, that's ok - you do it.

**Comment by MJLHThomassenHadrian** [comment]
Hey, its 2024 now and im running version 2.4.6 and having the exact same issue (Windows 11).
When i run a debug session, i get the output, but after any changes to parser/lexer file, i need to restart vscode for the changes to be picked up in another debug run. What could be the cause?
